### ISSUE TITLE
Value converters parameters

### ISSUE THREAD

**Issue by danfma** [durandalproject/aurelia#1]
Hey,

I just give a look at the documentation at http://jdanyow.github.io/aurelia-converters-sample/ and the framework is getting great!

I only have one point to discuss that is when using value converters with parameters. In the current documentation we have this kind of representation:

```html
<tr repeat.for="repo of repos | sort :column.value :direction.value | take:10">
```

So, why not just separate the parameters using comma ','? It looks a lot better and every programmer will try to separate using or comma or just creating an object with named values.

Proposition 1:

```html
<tr repeat.for="repo of repos | sort: column.value, direction.value | take:10">
```

Proposition 2:

```html
<tr repeat.for="repo of repos | sort:(column.value, direction.value) | take:10">
```

Proposition 3 (which is only one parameter object created on the fly):

```html
<tr repeat.for="repo of repos | sort: { source: column.value, direction: direction.value } | take:10">
```

**Comment by EisenbergEffect** [comment]
Please submit this to the aurelia/binding repo.
