### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by digitzfone** [durandalproject/aurelia#2]
We are scoping this out to look at converting our current site to a SPA and I am loving what I am seeing here. It is unclear to me how to change the scope in aurelia. In our current knockout architecture we us postbox to communicate between the default viewModel and page level viewModel. If we add a sub-viewmodel we can then use $parent, $parents[n], or $root to move up and down the scope. I am curious to see how aurelia handles communication between viewmodels and scope of connected viewmodels. Any help would be appreciated.

**Comment by EisenbergEffect** [comment]
@digitzfone Would you mind asking  about this in our gitter channel? https://gitter.im/Aurelia/Discuss  Thanks!
